apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-plugin-barman-cloud
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: cnpg-system
  releaseName: cnpg-plugin-barman-cloud
  chart:
    spec:
      chart: plugin-barman-cloud
      version: "0.3.1"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      interval: 12h
